name: Comment Pull Request

# on: [push]
# on: [pull_request]
on: 
  push: 
    branches: master

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      # - name: Check out code
      #   uses: actions/checkout@v4
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: console.log(context)
      - uses: actions/github-script@v7
        id: get_issue_number
        with:
          script: |
            const { data: list_comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
    
            // comment.user.login === 'github-actions[bot]'
            const bot_comment = list_comments.find(c => c.user.type === 'Bot' && c.user.id == 41898282 );
            const now = new Date().toLocaleString('zh', { timeZone: 'Asia/Taipei' });
            
            // const data = await github.rest.issues.updateComment({
            //   owner: context.repo.owner,
            //   repo: context.repo.repo,
            //   comment_id: bot_comment.id,
            //   body: `Updated from Github Actions. \n ${now}`,
            // });
            // console.log('updateComment data', data);
            
            github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: bot_comment.id,
            });
            console.log('Delete comment id', bot_comment.id);
            
            const { data } = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Greeting from Github Actions👋 \n ${now}`
            })
            console.log('Create comment id', data.id);

            return data.id;
          result-encoding: string
      - name: Result from github-script
        run: echo 'New created comment id ${{steps.get_issue_number.outputs.result}}'

