name: Labeler

# on: [pull_request]
# on:  
#   push:
#     branches:
#       - main
# on:
#   issues:
#     types:
#       - labeled
on:
  issues:
    types: [opened, edited, deleted]

jobs:
  add-label:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Test name
        run: |
          echo '${{ github.event }}'
      - uses: actions/github-script@v7
        id: update_label
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
          headRef: ${{ github.head_ref }}
          refName: ${{ github.ref_name }}
        with:
          script: |

            console.log('headRef', process.env.headRef)
            console.log('refName', process.env.refName)

            const isPullRequest = !!process.env?.pullRequet;
            console.log('isPullRequest', isPullRequest, process.env?.pullRequet);

            const isFeature = process.env?.BRANCH_NAME.toLowerCase().startsWith('feature') || process.env?.BRANCH_NAME.toLowerCase().startsWith('feat');
            const isBug = process.env?.BRANCH_NAME.toLowerCase().startsWith('fix');
            const isHotfix = process.env?.BRANCH_NAME.toLowerCase().startsWith('hotfix');
            const isRelease = process.env?.BRANCH_NAME.toLowerCase().startsWith('release');

            let labels = [];
            if (isFeature) labels.push('enhancement');
            if (isBug) labels.push('bug');
            if (isHotfix) labels.push('hotfix');
            if (isRelease) labels.push('release');
            
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels
            })
            return  process.env?.BRANCH_NAME
          result-encoding: string
      - name: Result from github-script
        run: echo 'Pull Request id ${{steps.update_label.outputs.result}}' 
    #   - uses: actions/labeler@v5
      