name: Test

on: [pull_request]
# on: 
#     push:
#       branches: ["master"]

jobs:
    UnitTest:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "20"
            cache: "npm"
        - name: Install dependenies
          run: npm install
        - name: Run Test
          id: test_and_report
          # Grep 4 rows after "Test Files", that's final info
          run: npm run test:ci --silent | grep -A 4 "Test Files" > ./test-reports.txt
          continue-on-error: true
        - name: Save Test result
          uses: actions/upload-artifact@v4
          id: artifact-upload-step
          with:
            name: test-reports
            path: ./test-reports.txt          
        - name: Log reports and check outcome
          run: |
            echo outcome: ${{ steps.test_and_report.outcome }}
            reports=$(<./test-reports.txt)
            echo $reports
            if [[ "${{ steps.test_and_report.outcome }}" == 'success' ]]; then
              exit 0
            else
              exit 1
            fi
        # - name: Exit if failure
        #   if: ${{ steps.test_and_report.outcome == 'failure' }}
        #   run: exit 1