name: UnitTest

# on: [pull_request]

on: 
    push:
      branches: ["master"]

jobs:
    UnitTest:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "20"
            cache: "npm"
        - name: Install dependenies
          run: npm install
        - name: Run Test
          id: test_and_report
          # Grep 4 rows after "Test Files", that's final info
          run:  |
            npm run test:ci --silent | grep -A 100 "Test Files" | sed -E "s/\x1B\[[0-9;]*[JKmsu]//g" > ./test_reports.txt
            npmExitCode=${PIPESTATUS[0]}
            echo "npmExitCode=$npmExitCode" >> "$GITHUB_ENV"
          continue-on-error: true
        - name: Save Test result
          uses: actions/upload-artifact@v4
          id: artifact-upload-step
          with:
            name: test_reports
            path: ./test_reports.txt          
        - name: Log reports and check outcome
          run: |
            echo npmExitCode: $npmExitCode
            echo outcome: ${{ steps.test_and_report.outcome }}
            if [[ "${{ steps.test_and_report.outcome }}" == 'failure'  || $npmExitCode == 1 ]]; then
              exit 1
            else
              exit 0
            fi